# Name of loaded config, to show to user
name = "PCSX2 debug settings"

# Default argument values
# Overwrite these from the command line
default_bsd = "ata"
default_bsdfs = "hdl"
default_dvd = "hdl:game.iso"
#default_ata0 = "no"
#default_ata0id = "no"
#default_ata1 = "no"
#default_mc0 = "no"
#default_mc1 = "no"
#default_elf = "cdrom0:I5BOOTN.ELF;1"
##default_mt = "dvd"
#default_gc = ""
#default_dbc = false
#default_logo = false

# Select the number of sectors for the FS buffer
# A small value can increase game compatibility
# A large value can increase performce
# Min=2, Max=128, Default=8
#cdvdman_fs_sectors = 2

# Override the 8-byte string returned by:
# - sceCdRI
# This string is also used by:
# - sceCdReadGUID
# - sceCdReadModelID
#
# This string is used (for instance) by the sony network configuration
# to verify if the config belongs to the specific console.
#
#ilink_id = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

# Use the 5-byte string returned by:
# - sceCdReadDiskID
#disk_id = [0x00, 0x00, 0x00, 0x00, 0x00]
