# Name of loaded config, to show to user
name = "PCSX2 debug settings"

#depends = ["rc-uya"]

# Default argument values
# Overwrite these from the command line
#default_bsd = "ata"
default_bsd = "usb"
#default_bsdfs = "exfat"

#default_dvd = "mass:DVD/Auto Modellista (E).iso"
#default_dvd = "mass:DVD/Disney's Treasure Planet (E).iso"
#default_dvd = "mass:DVD/Inuyasha - Feudal Combat (U).iso"
#default_dvd = "mass:DVD/Mobile Suit Gundam - Zeonic Front (U).iso"
#default_dvd = "mass:DVD/Scarface - The World Is Yours (U).iso"
#default_dvd = "mass:DVD/Silent Hill 3 (U).iso"
#default_dvd = "mass:DVD/Twisted Metal - Black (U).iso"
#default_dvd = "mass:CD/Twisted Metal - Black Online (USA).iso"
#default_dvd = "mass:DVD/Donkey Xote (E).iso"
#default_dvd = "mass:DVD/Gun (U).iso"
#default_dvd = "mass:DVD/Formula One 2001 (E).iso"
#default_dvd = "mass:CD/Tekken Tag Tournament (E) v2.iso"
#default_dvd = "mass:CD/Donald Duck - Goin' Quackers (U).iso"             # IOP reboot hang? ee_core?
#default_dvd = "mass:DVD/Donald Duck - Quack Attack (E).iso"              # IOP reboot hang? ee_core?
#default_dvd = "mass:DVD/Ratchet Clank - Up Your Arsenal (U).iso"
#default_dvd = "mass:DVD/Jak 3 (U).iso"
#default_dvd = "mass:CD/World Destruction League - Thunder Tanks (U).iso" # accurate reads too slow? use mode 0?
#default_dvd = "mass:DVD/Jackie Chan Adventures (E).iso"
#default_dvd = "mass:CD/Densha de Go! 3 - Tsuukin-hen (J).iso"
#default_dvd = "mass:DVD/Crash Twinsanity (U).iso"
#default_dvd = "mass:DVD/Fatal Frame (U).iso"
#default_dvd = "mass:DVD/Shadow Hearts - Covenant (U) (Disc 1).iso"
#default_dvd = "mass:DVD/Shadow Hearts - Covenant (U) (Disc 2).iso"
#default_dvd = "mass:DVD/Ibara (J).iso"

#default_ata0 = "no"
#default_ata0id = "no"
#default_ata1 = "no"
#default_mc0 = "no"
#default_mc1 = "no"
#default_elf = "cdrom0:I5BOOTN.ELF;1"
#default_mt = "dvd"
#default_gc = "0"
#default_cfg = "rc-uya"
#default_dbc = false
#default_logo = true

# Select the number of sectors for the FS buffer
# A small value can increase game compatibility
# A large value can increase performce
# Min=2, Max=128, Default=8
#cdvdman_fs_sectors = 2

# Override the 8-byte string returned by:
# - sceCdRI
# This string is also used by:
# - sceCdReadGUID
# - sceCdReadModelID
#
# This string is used (for instance) by the sony network configuration
# to verify if the config belongs to the specific console.
#
#ilink_id = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

# Use the 5-byte string returned by:
# - sceCdReadDiskID
#disk_id = [0x00, 0x00, 0x00, 0x00, 0x00]

#[[module]]
#file = "patch_freemem.irx"
#args = ["256", "X"]
#env = ["EE"]
