name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git bash p7zip

    - name: Workaround permission issue
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Compile project
      run: |
        make clean all

    - name: Compile debug build
      run: |
        wget https://github.com/israpps/ps2sdk/releases/download/IRX_debug/IRX.zip -O IRX.zip
        7z e IRX.zip
        make cleansrc all UDPTTY=1 EE_BIN_BASENAME=KELFBinder_debug_udpbd

    - name: Get short SHA
      id: slug
      run: |
        echo "SHA8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

    - name: build changelogs and move extra files
      run: |
        make changelog
        cp LICENSE bin/LICENSE.TXT

    - name: Get branch
      if: github.ref != 'refs/heads/MMCE'
      id: brnch
      run: |
        echo "BRANCH=$(echo -${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ env.SHA8 }}
        path: bin

    - name: Compress & Rename bin folder
      run: |
        echo Repository commit hash is: ${{ env.SHA8 }}>>bin/INSTALL/CORE/HASH.TXT
        echo if you report an issue to the developer. there is a high chance that he might ask you this code>>bin/INSTALL/CORE/HASH.TXT
        mv bin/ ${{ github.event.repository.name }}/
        7z a -t7z ${{ github.event.repository.name }}${{ env.BRANCH }}.7z ${{ github.event.repository.name }}/

    - name: Create prerelease
      if: github.ref == 'refs/heads/MMCE'
      uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "MMCE"
        title: "Latest development MMCE build"
        files: |
          ${{ github.event.repository.name }}${{ env.BRANCH }}.7z

    - name: Create prerelease
      if: startsWith(github.ref, 'refs/tags/v')
      uses: mathieucarbou/marvinpinto-action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "${{ env.BRANCH }}"
        title: "${{ env.BRANCH }}"
        files: |
          ${{ github.event.repository.name }}${{ env.BRANCH }}.7z
